project_id = "zlwvggnzyfldswpgebij"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://zlwvggnzyfldswpgebij.supabase.co"
additional_redirect_urls = ["http://localhost:5173", "https://zlwvggnzyfldswpgebij.supabase.co"]

[auth.hook.password_recovery]
enabled = true
uri = "https://zlwvggnzyfldswpgebij.supabase.co/functions/v1/send-reset-password-email"

[edge_functions]
enabled = true

[functions.send-email]
verify_jwt = true

[functions.send-marketing-email]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-reset-password-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-billing-portal-session]
verify_jwt = true

[functions.generate-store]
verify_jwt = true

[functions.create-manual-store]
verify_jwt = true

[functions.init-store]
verify_jwt = true

[functions.create-store]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.create-store-checkout]
verify_jwt = true

[functions.init-stripe-products]
verify_jwt = false

[functions.stripe-webhook-store]
verify_jwt = false

[functions.generate-ai-store]
verify_jwt = false